# This is only used for local development

version: '3'
services:
  redis:
    image: "redis:alpine"
    entrypoint:
      redis-server --appendonly yes --port 6380
    volumes:
      - ~/.cache/beta:/redis/data
    ports:
      - "6380:6380"
  web:
    build:
      context: .
      args:
        version: 'latest'
    entrypoint: npm run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    env_file:
      - .env-beta
    depends_on:
      - redis
    links:
      - redis
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    links:
      - web
    environment:
      - NGROK_SUBDOMAIN=uplink-slack-beta
      - NGROK_REGION=eu
      - NGROK_PORT=web:3001
    env_file:
      - .env-beta
    depends_on:
      - web
