# This is only used for local development

version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    entrypoint: npm run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
  localtunnel:
    image: efrecon/localtunnel
    command:
      --port 3000 --subdomain open-convo-slack --local-host web
    depends_on:
      - web