# This is only used for local development

version: '3'
services:
  redis_beta:
    image: "redis:alpine"
    entrypoint:
      redis-server --appendonly yes
    ports:
      - "6380:6379"
  web_beta:
    build:
      context: .
      args:
        version: 'latest'
    entrypoint: npm run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3000"
    env_file:
      - .env-beta
    depends_on:
      - redis_beta
    links:
      - redis_beta
  ngrok_beta:
    image: wernight/ngrok
    ports:
      - "4041:4040"
    links:
      - web_beta
    environment:
      - NGROK_SUBDOMAIN=uplink-slack-beta
      - NGROK_REGION=eu
      - NGROK_PORT=web_beta:3000
    env_file:
      - .env-beta
    depends_on:
      - web_beta
